### ISSUE TITLE
[SOLVED but...] Query.Limit is ignored by Find(Query)

### ISSUE THREAD

**Issue by nightroman** [litedb-org/LiteDB#1506]
UPDATE: The problem seems to be in the unusual API design, see next comments.

**Version**

LiteDB 5.0.3 and the latest from repo, Windows 10, net45

**Describe the bug**

`Query.Limit` is ignored by collection `Find(Query)`.

**Code to Reproduce**

```csharp
[Fact]
public void Query_Limit()
{
    using (var db = new LiteDatabase(":memory:"))
    {
        var col = db.GetCollection("Test");
        col.Insert(new BsonDocument { ["_id"] = 1 });
        col.Insert(new BsonDocument { ["_id"] = 2 });
        col.Count().Should().Be(2);

        var query = new Query();
        query.Limit = 1;
        var r = col.Find(query).ToList();
        r.Count.Should().Be(1); // ~ fails, actual is 2
    }
}
```

**Expected behavior**

The above test is expected to pass, `Query.Limit` set to 1 should result in 1 result document, not actual 2.

**Comment by nightroman** [comment]
And a side note (let me know if it's worth another issue to open).

From ILSpy, this the code of another `Find(Query, int, int)`:

```csharp
public IEnumerable<T> Find(Query query, int skip = 0, int limit = int.MaxValue)
{
    if (query == null)
    {
        throw new ArgumentNullException("query");
    }
    query.Offset = skip;
    query.Limit = limit;
    return new LiteQueryable<T>(_engine, _mapper, _collection, query).ToEnumerable();
}
```

This code changes the input `query`. This does not look quite right.
The `query` may be used later in `Find(Query)` with unexpectedly changed `Limit` and `Offset`.

**Comment by nightroman** [comment]
Ah, I get it... The two issues are in fact one. `Find` with default skip and limit parameters overrides my `Offset` and `Limit` settings in the passed `query`.

Is this design deliberate and thought through?
If yes, please close the issue.

**Comment by lbnascimento** [comment]
@nightroman, thank you for your question. This behavior is not intended and is fixed in the master branch. It should be present in the next incremental release.

**Comment by nightroman** [comment]
Thank you.

```
-            query.Offset = skip;
-            query.Limit = limit;
+            if(skip != 0) query.Offset = skip;
+            if(limit != int.MaxValue) query.Limit = limit;
```

It's still does not look quite right (to me). Because non-default parameters still change the input `query` and if this `query` is used afterwards on it's own this change may be unexpected.

If `Query` have `Offset` and `Limit` then why are these parameters at all? (Thinking out loud...)

**Comment by nightroman** [comment]
I think the fix is not quite right, see my comment. Should we reopen the issue? Should I create a new issue? Please let me know.

**Comment by lbnascimento** [comment]
@nightroman Do you have any suggestion on how to properly fix this? I could do something like I did in #1549 , but it's too hacky for me. In my opinion, the Query class should be refactored and made into an immutable class, but it seems too complicated given that it contains BsonExpressions and lists of BsonExpression.

**Comment by nightroman** [comment]
I know it's a potentially breaking change (minor) but at the current state of things (still adopting v5) I would remove the method with `Offset` and `Limit` parameters. This resolves the problems. **Users** set `Offset` and `Limit` in the query instance, so that it's their responsibility to set new values if they are using the same instance 2+ times.

**Comment by nightroman** [comment]
These parameters are **unexpected** in the method from my point of view, and **inconsistent**, too. Why just them and not others? For example, why `Order` is not added to the same method with default value `1`? And so on. `Find` should take just `Query`. Classic pattern with parameters object which type could be called `FindArgs` (but conveniently called `Query` in our case, the only difference).
