### ISSUE TITLE
[BUG] slot length must be empty before use

### ISSUE THREAD

**Issue by HolyOne** [litedb-org/LiteDB#2134]
I have a collection named Doc
It has a   public string[] Keywords { get; set; }
My database was working fine I had a lot of documents.
but yesterday I got this error when inserting new document.

Exception [ System.Exception ] : LiteDB ENSURE: slot length must be empty before use 

I tried to reproduce the problem. I only get this message on server, not on my local dev environment.
I only get this error if I input more than 3 keywords to my record.
I had a lot of documents before which had more than 3 keywords. 
I suspect this is a bug. Can you explain this error?

**Comment by HolyOne** [comment]
I fixed it by opening it in LiteDB studio and chose Rebuild.
But still there was no reason for it to be corrupted.
Maybe the library can perform rebuild internally in case of such errors

**Comment by kcsombrio** [comment]
Hi @HolyOne, we fixed issue #2129 which was showing the same error message, but we didn't build it into the next release yet. Would you be able to test your case with the latest code on master branch?

In the case of #2129, the problem happened with the indexing system, so my question is: did this error happen after you added an extra index, i.e, using EnsureIndex()?

**Comment by HolyOne** [comment]
@kcsombrio

I use ensureIndex every time I initalize database entity. The collection had multiple indexes so i guess so.

**Comment by narcis-ro** [comment]
Yup. Apparently we also ensure index. I guess that’s the diff between our code and the studio. But I still can’t figure why moving the db file to a local machine (that also does ensure index) the problem doesn’t reproduce

**Comment by eugeniaparvulescu** [comment]
I'm a colleague of narcis-ro, I have the same error.
After testing with the latest code from master it also reproduces on the local machine.

**Comment by JKamsker** [comment]
This ENSURE fires when LiteDB tries to reuse a slot in a page that isn't actually free. With a multikey (`string[]`) index, one insert adds several keys to the same index page. Enough keys could trigger a page defragmentation, after which the engine still held a stale reference to the previous index node. That is the bug from #2129, and it fits "only with more than 3 keywords". It was fixed in 5.0.12 (03b25793, with a regression test).

The fix prevents new corruption but can't repair a file that is already damaged, which is why testing master against an already broken file still failed. Run `db.Rebuild()` once, or use Rebuild in LiteDB Studio as you did, and the file is clean again.

The "stored slot must be same as called" error after power loss, reported further down this thread, is a different problem and is tracked in #1984.

Latest version:

```
dotnet add package LiteDB --prerelease
```

If this doesn't cover your case, comment here and we'll reopen it.
